import { c as create_ssr_component } from "../../chunks/ssr.js";
const css = {
  code: ':root{--bg:#fff;--accent:black;--border:2px solid var(--accent);font-family:Inter}body{margin:0}p{font-weight:300;font-size:1.3em}h1{font-family:Durer;font-size:2.5em;font-weight:100;line-height:1.1}button{all:unset;cursor:pointer;border-bottom:1px solid var(--accent);-webkit-touch-callout:none;-webkit-user-select:none;-moz-user-select:none;user-select:none;transition:0.1s}a{all:unset;cursor:pointer;border-bottom:1px solid var(--accent);-webkit-touch-callout:none;-webkit-user-select:none;-moz-user-select:none;user-select:none;transition:0.1s}a:hover{border-bottom:5px solid black;transition:0.1s}button:hover{border-bottom:5px solid black;transition:0.1s}@font-face{font-family:Durer;src:url("$lib/fonts/IFDurerDisplay.woff")}@font-face{font-family:Inter;src:url("$lib/fonts/Inter-Medium.woff")}',
  map: '{"version":3,"file":"+layout.svelte","sources":["+layout.svelte"],"sourcesContent":["<script>\\n  import \\"../app.pcss\\";\\n<\/script>\\n\\n<svelte:head>\\n  <link rel=\\"preconnect\\" href=\\"https://fonts.googleapis.com\\" />\\n  <link rel=\\"preconnect\\" href=\\"https://fonts.gstatic.com\\" crossorigin />\\n  <link\\n    href=\\"https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&family=Inter:wght@100..900&family=Ysabeau+Office:ital,wght@0,1..1000;1,1..1000&display=swap\\"\\n    rel=\\"stylesheet\\"\\n  />\\n</svelte:head>\\n\\n<slot />\\n\\n<style>\\n  :root {\\n    --bg: #fff; /*#f3e7db;*/\\n    --accent: black;\\n    --border: 2px solid var(--accent);\\n    font-family: Inter;\\n  }\\n  :global(body) {\\n    margin: 0;\\n    /*font-family: Inter;*/\\n  }\\n  :global(p) {\\n    font-weight: 300;\\n    font-size: 1.3em;\\n  }\\n  :global(h1) {\\n    font-family: Durer;\\n    font-size: 2.5em;\\n    font-weight: 100;\\n    line-height: 1.1;\\n  }\\n  :global(button) {\\n    all: unset;\\n    cursor: pointer;\\n    border-bottom: 1px solid var(--accent);\\n    -webkit-touch-callout: none;\\n    -webkit-user-select: none;\\n    -moz-user-select: none;\\n    user-select: none;\\n    transition: 0.1s;\\n  }\\n  :global(a) {\\n    all: unset;\\n    cursor: pointer;\\n    border-bottom: 1px solid var(--accent);\\n    -webkit-touch-callout: none;\\n    -webkit-user-select: none;\\n    -moz-user-select: none;\\n    user-select: none;\\n    transition: 0.1s;\\n  }\\n  :global(a:hover) {\\n    border-bottom: 5px solid black;\\n    transition: 0.1s;\\n  }\\n  :global(button:hover) {\\n    border-bottom: 5px solid black;\\n    transition: 0.1s;\\n  }\\n  @font-face {\\n    font-family: Durer;\\n    src: url(\\"$lib/fonts/IFDurerDisplay.woff\\");\\n  }\\n  @font-face {\\n    font-family: Inter;\\n    src: url(\\"$lib/fonts/Inter-Medium.woff\\");\\n  }\\n</style>\\n"],"names":[],"mappings":"AAgBE,KAAM,CACJ,IAAI,CAAE,IAAI,CACV,QAAQ,CAAE,KAAK,CACf,QAAQ,CAAE,uBAAuB,CACjC,WAAW,CAAE,KACf,CACQ,IAAM,CACZ,MAAM,CAAE,CAEV,CACQ,CAAG,CACT,WAAW,CAAE,GAAG,CAChB,SAAS,CAAE,KACb,CACQ,EAAI,CACV,WAAW,CAAE,KAAK,CAClB,SAAS,CAAE,KAAK,CAChB,WAAW,CAAE,GAAG,CAChB,WAAW,CAAE,GACf,CACQ,MAAQ,CACd,GAAG,CAAE,KAAK,CACV,MAAM,CAAE,OAAO,CACf,aAAa,CAAE,GAAG,CAAC,KAAK,CAAC,IAAI,QAAQ,CAAC,CACtC,qBAAqB,CAAE,IAAI,CAC3B,mBAAmB,CAAE,IAAI,CACzB,gBAAgB,CAAE,IAAI,CACtB,WAAW,CAAE,IAAI,CACjB,UAAU,CAAE,IACd,CACQ,CAAG,CACT,GAAG,CAAE,KAAK,CACV,MAAM,CAAE,OAAO,CACf,aAAa,CAAE,GAAG,CAAC,KAAK,CAAC,IAAI,QAAQ,CAAC,CACtC,qBAAqB,CAAE,IAAI,CAC3B,mBAAmB,CAAE,IAAI,CACzB,gBAAgB,CAAE,IAAI,CACtB,WAAW,CAAE,IAAI,CACjB,UAAU,CAAE,IACd,CACQ,OAAS,CACf,aAAa,CAAE,GAAG,CAAC,KAAK,CAAC,KAAK,CAC9B,UAAU,CAAE,IACd,CACQ,YAAc,CACpB,aAAa,CAAE,GAAG,CAAC,KAAK,CAAC,KAAK,CAC9B,UAAU,CAAE,IACd,CACA,UAAW,CACT,WAAW,CAAE,KAAK,CAClB,GAAG,CAAE,qCACP,CACA,UAAW,CACT,WAAW,CAAE,KAAK,CAClB,GAAG,CAAE,mCACP"}'
};
const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-1qfu89k_START --><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&family=Inter:wght@100..900&family=Ysabeau+Office:ital,wght@0,1..1000;1,1..1000&display=swap" rel="stylesheet"><!-- HEAD_svelte-1qfu89k_END -->`, ""} ${slots.default ? slots.default({}) : ``}`;
});
export {
  Layout as default
};
